# Generated by Django 6.0.6 on 2026-07-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('EQUIPMENT', 'Equipment'), ('VEHICLE', 'Vehicle'), ('IT', 'IT Asset'), ('FURNITURE', 'Furniture'), ('BUILDING', 'Building'), ('OTHER', 'Other')], default='EQUIPMENT', max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('INACTIVE', 'Inactive'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=30)),
                ('location', models.CharField(max_length=150)),
                ('manufacturer', models.CharField(blank=True, max_length=150)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['asset_code'],
            },
        ),
    ]
